import type { SourceDefinition } from "./types";

export const sources: SourceDefinition[] = [
  {
    id: "npu-telegram",
    name: "Національна поліція України",
    kind: "official",
    transport: "telegram",
    url: "https://t.me/s/UA_National_Police",
    telegramChannel: "UA_National_Police",
    canonicalHosts: [
      "npu.gov.ua",
      "www.npu.gov.ua",
      "ch.npu.gov.ua",
      "cn.npu.gov.ua",
      "cr.npu.gov.ua",
      "dn.npu.gov.ua",
      "dp.npu.gov.ua",
      "hk.npu.gov.ua",
      "hm.npu.gov.ua",
      "hr.npu.gov.ua",
      "if.npu.gov.ua",
      "kg.npu.gov.ua",
      "kv.npu.gov.ua",
      "lg.npu.gov.ua",
      "mk.npu.gov.ua",
      "od.npu.gov.ua",
      "pl.npu.gov.ua",
      "su.npu.gov.ua",
      "tp.npu.gov.ua",
      "zk.npu.gov.ua",
      "zp.npu.gov.ua",
      "vn.npu.gov.ua",
      "rv.npu.gov.ua",
      "vl.npu.gov.ua",
      "cv.npu.gov.ua",
      "zt.npu.gov.ua",
      "kyiv.npu.gov.ua",
      "lv.npu.gov.ua",
    ],
    cadenceMinutes: 60,
    verificationUrl:
      "https://if.npu.gov.ua/news/natspolitsiya-zapustila-shche-odin-nomer-garyachoi-linii-z-poshuku-zniklikh-chi-zagiblikh-vnaslidok-viyskovikh-diy-rf-v-ukraini",
  },
  {
    id: "npu-vinnytsia-telegram",
    name: "Поліція Вінницької області",
    kind: "official",
    transport: "telegram",
    url: "https://t.me/s/vinnpol",
    telegramChannel: "vinnpol",
    regionCode: "23",
    canonicalHosts: ["vn.npu.gov.ua"],
    cadenceMinutes: 60,
    verificationUrl:
      "https://npu.gov.ua/static-objects/npu/sites/1/uploaded-files/zvit-shhodo-zdiisnennia-zaxodiv-z-realizaciyi-nacstrategiyi-v-castini-fizicnoyi-dostupnosti-2025.pdf",
  },
  {
    id: "npu-rivne-telegram",
    name: "Поліція Рівненської області",
    kind: "official",
    transport: "telegram",
    url: "https://t.me/s/NPU_Rivne",
    telegramChannel: "NPU_Rivne",
    regionCode: "19",
    canonicalHosts: ["rv.npu.gov.ua"],
    cadenceMinutes: 60,
    verificationUrl:
      "https://rv.npu.gov.ua/news/ochilnyk-politsii-rivnenshchyny-viktor-shanskyi-vidznachyv-politseiskykh-ta-vruchyv-spetsialni-zvannia",
  },
  {
    id: "npu-volyn-telegram",
    name: "Поліція Волинської області",
    kind: "official",
    transport: "telegram",
    url: "https://t.me/s/policevolyn",
    telegramChannel: "policevolyn",
    regionCode: "24",
    canonicalHosts: ["vl.npu.gov.ua"],
    cadenceMinutes: 60,
    verificationUrl:
      "https://vl.npu.gov.ua/news/de-otrymaty-ofitsiinu-operatyvnu-informatsiiu-vid-politsii-volyni-u-razi-problem-z-robotoiu-saitu",
  },
  {
    id: "npu-chernivtsi-telegram",
    name: "Поліція Чернівецької області",
    kind: "official",
    transport: "telegram",
    url: "https://t.me/s/police_bukovina",
    telegramChannel: "police_bukovina",
    regionCode: "03",
    canonicalHosts: ["cv.npu.gov.ua"],
    cadenceMinutes: 60,
    verificationUrl:
      "https://cv.npu.gov.ua/news/pidpysuitesia-na-informatsiini-resursy-politsii-bukovyny",
  },
  {
    id: "npu-zhytomyr-telegram",
    name: "Поліція Житомирської області",
    kind: "official",
    transport: "telegram",
    url: "https://t.me/s/zt_police",
    telegramChannel: "zt_police",
    regionCode: "27",
    canonicalHosts: ["zt.npu.gov.ua"],
    cadenceMinutes: 60,
    verificationUrl:
      "https://npu.gov.ua/static-objects/npu/sites/22/Docs/Anticorruption/2025/dodatok-3-navcannia.pdf",
  },
  {
    id: "patrol-rss",
    name: "Патрульна поліція України",
    kind: "official",
    transport: "rss",
    url: "https://patrolpolice.gov.ua/feed/",
    verificationUrl: "https://patrolpolice.gov.ua/",
  },
  {
    id: "ukrinform-regions",
    name: "Укрінформ",
    kind: "media",
    transport: "rss",
    url: "https://www.ukrinform.ua/rss/rubric-regions",
    verificationUrl: "https://www.ukrinform.ua/",
    archiveUrl: "https://www.ukrinform.ua/rubric-regions/block-lastnews",
  },
  {
    id: "zaxid-news",
    name: "ZAXID.NET",
    kind: "media",
    transport: "rss",
    url: "https://zaxid.net/rss/1.xml",
    verificationUrl: "https://zaxid.net/home/showRss.do",
  },
  {
    id: "npu-news",
    name: "Нацполіція — вебсайт",
    kind: "official",
    transport: "police-web",
    url: "https://npu.gov.ua/timeline?type=posts",
    verificationUrl: "https://npu.gov.ua/",
  },
  {
    id: "kyiv-police-news",
    name: "Поліція Києва",
    kind: "official",
    transport: "police-web",
    url: "https://kyiv.npu.gov.ua/timeline?type=posts",
    verificationUrl: "https://kyiv.npu.gov.ua/",
  },
  {
    id: "lviv-police-news",
    name: "Поліція Львівщини",
    kind: "official",
    transport: "police-web",
    url: "https://lv.npu.gov.ua/timeline?type=posts",
    verificationUrl: "https://lv.npu.gov.ua/",
  },
  {
    id: "court-decisions",
    name: "Єдиний державний реєстр судових рішень",
    kind: "court",
    transport: "court",
    url: "https://data.gov.ua/dataset/ediniy-derzhavniy-reestr-sudovih-rishen-za-2026-rik_7636",
    verificationUrl:
      "https://data.gov.ua/organization/derzhavna-sudova-administratsiia-ukrayiny",
  },
];
export const sourceById = (id: string) =>
  sources.find((source) => source.id === id);
export const scheduledSources = sources.filter(
  (source) => source.transport !== "court",
);
